# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import test1_pb2 as test1__pb2


class AudioStreamingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAudio = channel.unary_stream(
                '/test1.AudioStreaming/GetAudio',
                request_serializer=test1__pb2.Text.SerializeToString,
                response_deserializer=test1__pb2.Audio.FromString,
                )


class AudioStreamingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioStreamingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAudio': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAudio,
                    request_deserializer=test1__pb2.Text.FromString,
                    response_serializer=test1__pb2.Audio.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'test1.AudioStreaming', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AudioStreaming(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/test1.AudioStreaming/GetAudio',
            test1__pb2.Text.SerializeToString,
            test1__pb2.Audio.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
